#spring.application.name=cloudstorage
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/cloudstorage_test
#spring.datasource.username=postgres
#spring.datasource.password=mayank
#
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#
#jwt.algorithm.key=ajsjfhaurrhueaksgaisgfkas
#jwt.issuer=mayank
#jwt.expiry.duration=86400000