

spring:
  application:
    name: cloudstorage

  datasource:
    url: jdbc:postgresql://localhost:5432/cloudstorage_test
    username: postgres
    password: mayank
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ....-5eip77fub4ia40m4jga0090ll8s39s1b.apps.googleusercontent.com
            client-secret: ....-ObKefnMC-LNMCCWpLeahJAcjpDMk
            scope:
              - openid
              - profile
              - email


jwt:
  algorithm:
    key: ${JWT_ALGORITHM_KEY:ajsjfhaurrhueaksgaisgfkas}

  issuer: cloudstorage

  expiry:
    duration: 86400000


aws:
  s3:
    bucket-name: cloudstorage24
    region: ap-south-1
    access-key: ...3EGUP4IE74DZ5ZY
    secret-key: ......EvrLsWKWUa24qszIza2s8ufGNB+tndK
